# This yaml file is used for storing relevant endpoints

endpoints:
  # Studentmgmnt Endpoints
  create_student: '/studentmgmt/addStudent'
  delete_student: '/studentmgmt/deleteStudent'
  get_student: '/studentmgmt/fetchStudents'
  update_student: '/studentmgmt/updateStudent'